# fly.toml app configuration file generated for temporal-global-citizen-server on 2024-03-06T10:58:00+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'temporal-global-citizen-server'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.21.5'

[env]
  GOOGLE_APPLICATION_CREDENTIALS = '/usr/local/bin/temporal-global-citizen-db0309516509.json'
  PORT = '8080'
  WALLET_ISSUER_ID = '3388000000022320241'

[http_service]
  force_https = false
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
